INSERT INTO nationalities (nationality)
VALUES 
('Afghan'),
('Albanian'),
('Algerian'),
('American Samoan'),
('Andorran'),
('Angolan'),
('Anguillan'),
('Antarctic'),
('Antiguan and Barbudan'),
('Argentine'),
('Armenian'),
('Aruban'),
('Australian'),
('Austrian'),
('Azerbaijani'),
('Bahamian'),
('Bahraini'),
('Bangladeshi'),
('Barbadian'),
('Belarusian'),
('Belgian'),
('Belizean'),
('Beninese'),
('Bermudian'),
('Bhutanese'),
('Bolivian'),
('Bonaire, Sint Eustatius and Saba'),
('Bosnian and Herzegovinian'),
('Motswana'),
('Bouvet Island'),
('Brazilian'),
('British Indian Ocean Territory'),
('Bruneian'),
('Bulgarian'),
('Burkinabé'),
('Burundian'),
('Cabo Verdean'),
('Cambodian'),
('Cameroonian'),
('Canadian'),
('Caymanian'),
('Central African'),
('Chadian'),
('Chilean'),
('Chinese'),
('Christmas Island'),
('Cocos Islander'),
('Colombian'),
('Comoran'),
('Congolese'),
('Congolese'),
('Cook Islander'),
('Costa Rican'),
('Croatian'),
('Cuban'),
('Curaçaoan'),
('Cypriot'),
('Czech'),
('Ivorian'),
('Danish'),
('Djiboutian'),
('Dominican'),
('Dominican'),
('Ecuadorian'),
('Egyptian'),
('Salvadoran'),
('Equatorial Guinean'),
('Eritrean'),
('Estonian'),
('Eswatini'),
('Ethiopian'),
('Falkland Islander'),
('Faroese'),
('Fijian'),
('Finnish'),
('French'),
('French Guianese'),
('French Polynesian'),
('French Southern Territories'),
('Gabonese'),
('Gambian'),
('Georgian'),
('German'),
('Ghanaian'),
('Gibraltar'),
('Greek'),
('Greenlandic'),
('Grenadian'),
('Guadeloupean'),
('Guamanian'),
('Guatemalan'),
('Channel Islander'),
('Guinean'),
('Bissau-Guinean'),
('Guyanese'),
('Haitian'),
('Heard Island and McDonald Islands'),
('Vatican'),
('Honduran'),
('Hong Kong'),
('Hungarian'),
('Icelandic'),
('Indian'),
('Indonesian'),
('Iranian'),
('Iraqi'),
('Irish'),
('Manx'),
('Italian'),
('Jamaican'),
('Japanese'),
('Jersey'),
('Jordanian'),
('Kazakhstani'),
('Kenyan'),
('I-Kiribati'),
('North Korean'),
('South Korean'),
('Kuwaiti'),
('Kyrgyzstani'),
('Laotian'),
('Latvian'),
('Lebanese'),
('Mosotho'),
('Liberian'),
('Libyan'),
('Liechtensteiner'),
('Lithuanian'),
('Luxembourger'),
('Macanese'),
('Malagasy'),
('Malawian'),
('Malaysian'),
('Maldivian'),
('Malian'),
('Maltese'),
('Marshallese'),
('Martiniquais'),
('Mauritanian'),
('Mauritian'),
('Mahoran'),
('Mexican'),
('Micronesian'),
('Moldovan'),
('Monégasque'),
('Mongolian'),
('Montenegrin'),
('Montserratian'),
('Moroccan'),
('Mozambican'),
('Myanmarian'),
('Namibian'),
('Nauruan'),
('Nepali'),
('Dutch'),
('New Caledonian'),
('New Zealand'),
('Nicaraguan'),
('Nigerien'),
('Nigerian'),
('Niuean'),
('Norfolk Islander'),
('North Macedonian'),
('Northern Mariana Islander'),
('Norwegian'),
('Omani'),
('Pakistani'),
('Palauan'),
('Palestinian'),
('Panamanian'),
('Papua New Guinean'),
('Paraguayan'),
('Peruvian'),
('Filipino'),
('Pitcairn Islander'),
('Polish'),
('Portuguese'),
('Puerto Rican'),
('Qatari'),
('Romanian'),
('Russian'),
('Rwandan'),
('Réunionese'),
('Saint Barthélemy Islander'),
('Saint Helenian'),
('Saint Kitts and Nevisian'),
('Saint Lucian'),
('Saint Martin Islander'),
('Saint Pierre and Miquelon'),
('Saint Vincentian'),
('Samoan'),
('San Marinese'),
('São Toméan'),
('Saudi Arabian'),
('Senegalese'),
('Serbian'),
('Seychellois'),
('Sierra Leonean'),
('Singaporean'),
('Sint Maarten Islander'),
('Slovak'),
('Slovenian'),
('Solomon Islander'),
('Somali'),
('South African'),
('South Georgia Islander'),
('South Sudanese'),
('Spanish'),
('Sri Lankan'),
('Sudanese'),
('Surinamese'),
('Svalbard and Jan Mayen Islander'),
('Swedish'),
('Swiss'),
('Syrian'),
('Taiwanese'),
('Tajikistani'),
('Tanzanian'),
('Thai'),
('Timorese'),
('Togolese'),
('Tokelauan'),
('Tongan'),
('Trinidadian or Tobagonian'),
('Tunisian'),
('Turkish'),
('Turkmen'),
('Turks and Caicos Islander'),
('Tuvaluan'),
('Ugandan'),
('Ukrainian'),
('Emirati'),
('British'),
('American'),
('US Virgin Islander'),
('Uruguayan'),
('Uzbekistani'),
('Ni-Vanuatu'),
('Venezuelan'),
('Vietnamese'),
('Wallisian and Futunan'),
('Sahrawi'),
('Yemeni'),
('Zambian'),
('Zimbabwean');
GO

select * from users